apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: openshift-migrationproxy
  name: openshift-migrationproxy
spec:
  replicas: 2
  selector:
    app: openshift-migrationproxy
    deploymentconfig: openshift-migrationproxy
  strategy:
    resources: {}
    rollingParams:
      maxSurge: 25%
      maxUnavailable: 25%
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-migrationproxy
        deploymentconfig: openshift-migrationproxy
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: openshift-migrationproxy:latest
      resources: {}
      source:
        git:
          ref: master
          uri: git@github.com:ure/openshift-migrationproxy.git
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: centos:7
        type: Docker
      containers:
      - image: openshift-migrationproxy
        imagePullPolicy: Always
        name: openshift-migrationproxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-migrationproxy
      from:
        kind: ImageStreamTag
        name: openshift-migrationproxy:latest
    type: ImageChange
status: {}
